import React from 'react';
import type { Metadata } from 'next';
import '@/styles/globals.css';
import '@/styles/main.css';
import AuthProvider from '@/context/AuthProvider';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/utils/theme-provider';
import Header from '@/features/website/header';
import Providers from '../provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn('relative antialiased min-h-screen bg-background pb-8')}
      >
        <Providers>
          <AuthProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Header />
              <div className="section-container pt-[.5rem]">{children}</div>
            </ThemeProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
