-- Schema definition for Supabase database

-- 1. Profiles Table (Synced with auth.users)
create table public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  username text unique,
  first_name text,
  last_name text,
  phone text,
  bio text,
  profile_picture text,
  role text default 'USER',
  status text default 'ACTIVE',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can update their own profile." on public.profiles
  for update using (auth.uid() = id);

-- Trigger function to handle new auth users
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, first_name, last_name, phone, role, status)
  values (
    new.id,
    new.raw_user_meta_data->>'username',
    new.raw_user_meta_data->>'firstName',
    new.raw_user_meta_data->>'lastName',
    new.phone,
    coalesce(new.raw_user_meta_data->>'role', 'USER'),
    'ACTIVE'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger execution
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Projects Table
create table public.projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  technologies text[] not null,
  link text,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for projects
alter table public.projects enable row level security;

create policy "Projects are viewable by everyone." on public.projects
  for select using (true);

create policy "Only admins can modify projects." on public.projects
  for all using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'ADMIN'
    )
  );

-- 3. Experiences Table
create table public.experiences (
  id bigint generated by default as identity primary key,
  date_range text not null,
  title text not null,
  place text not null,
  type text check (type in ('EDUCATION', 'WORK')) not null,
  sort_order integer default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for experiences
alter table public.experiences enable row level security;

create policy "Experiences are viewable by everyone." on public.experiences
  for select using (true);

create policy "Only admins can modify experiences." on public.experiences
  for all using (
    exists (
      select 1 from public.profiles
      where profiles.id = auth.uid() and profiles.role = 'ADMIN'
    )
  );

-- Seed initial projects data
insert into public.projects (title, description, technologies, link, image_url) values
('Gimmefy AI', 'AI-Enhanced Marketing Platform with 150+ automated tasks and personalized AI assistants designed for marketers, by marketers.', array['React', 'TypeScript', 'Mantine', 'Redux Toolkit'], 'https://gimmefy.ai', null),
('Dialmantra Dialer', 'Fast, easy and low cost solution to run a world class contact center without huge investments on hardware and software.', array['React.js', 'Redux.js', 'JavaScript', 'JSSIP', 'HTML', 'Ant Design', 'LESS'], 'https://www.dialmantra.in/', null),
('Amotus Online', 'Amotus Online stands as an innovative remote screen sharing platform, offering a unique solution for enhanced collaboration and communication.', array['React', 'Node.js', 'MongoDB', 'Express'], 'https://amotus.online/', null),
('Drishti IAS Website', 'Improved institute website user interface and experience through collaborative efforts.', array['JavaScript', 'HTML', 'CSS', 'API Integration'], 'https://drishtiias.com', null);

-- Seed initial experiences data (WORK)
insert into public.experiences (date_range, title, place, type, sort_order) values
('12/2023 - Present', 'Front-End Developer (Product- AI Marketing Tools)', 'Gimmefy AI - Remote', 'WORK', 1),
('06/2022 - 10/2023', 'Front-End Developer (Products- Amotus online, Diamantra dialer, Call Center CRM)', 'Collaberus technologies pvt. ltd. - Delhi', 'WORK', 2),
('10/2021 - 06/2022', 'Front-End & Technical Associate', 'Drishti IAS - Delhi', 'WORK', 3);

-- Seed initial experiences data (EDUCATION)
insert into public.experiences (date_range, title, place, type, sort_order) values
('2022 - 2023', 'Bachelor of Computer Applications', 'Capital University, Jharkhand (First Division)', 'EDUCATION', 1),
('2018 - 2021', 'CSE Diploma', 'B.B.S.B.P. College, Sirhind, PSBTE & IT, Chandigarh (First Division)', 'EDUCATION', 2),
('2018', 'High School', 'Guru Nanak Public Sr. Sec School, CBSE, Kanpur (First Division)', 'EDUCATION', 3);
