import React from 'react';
import type { Metadata } from 'next';
import '@/styles/globals.css';
import '@/styles/main.css';
import AuthProvider from '@/context/AuthProvider';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/utils/theme-provider';
import Header from '@/features/website/header';
import Navbar from '@/features/website/navbar';
import ProfileSideSection from '@/features/website/profile-side-section';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'antialiased h-screen bg-background overflow-hidden sm:overflow-auto'
        )}
      >
        <AuthProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Header />
            <div className="section-container pt-[4rem] sm:pb-4">
              <Navbar />
              <div className="flex gap-3 sm:flex-col sm:items-center">
                <ProfileSideSection />
                {children}
              </div>
            </div>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
